apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vault-unavailable
  description: Plugin to unavailable vault
  tags:
    - vault
    - plugin
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: platform
