apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage sub-department
spec:
  type: sub-department
  profile:
    displayName: Backstage
    email: backstage@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: infrastructure
  children: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: chapter
  description: Everything related to chapter
  title: Chapter
spec:
  owner: team-a
