apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: location-resources
  description: A collection of all Backstage example resources
spec:
  targets:
    - https://github.com/Tomelin/platform/blob/main/templates/backstage/resources/all-resources.yaml
